math_theory/urls.py
from django.contrib import admin
from django.urls import include,path
from theory import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('theory/', include('theory.urls')),
    path('questions/', include('questions.urls')),
    path('tasks/', include('tasks.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.questions, name='questions'),
    path('<int:questions_id>', views.detail, name='detail'),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.tasks, name='tasks'),
    path('<int:tasks_id>', views.detail, name='detail'),
]

theory/urls.py
from django.urls import path
from . import views

app_name = 'theory'

urlpatterns = [
    path('', views.theory, name='theory'),
    path('<int:theory_id>', views.detail, name='detail'),
]

questions/models.py
from django.db import models


class Question(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

tasks/models.py
from django.db import models


class Tasks(models.Model):
    title = models.CharField(max_length=100)
    description = models.FileField(upload_to='tasks/files/', blank=True)

    def __str__(self):
        return self.title

theory/models.py
from django.db import models


class Theory(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

questions/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Question


def questions(request):
    questions = Question.objects.all()
    return render(request, 'questions/questions.html', {'questions': questions})


def detail(request, questions_id):
    questions = get_object_or_404(Question, pk=questions_id)
    return render(request, 'questions/detail.html', {'questions': questions})

tasks/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Tasks


def tasks(request):
    tasks = Tasks.objects.all()
    return render(request, 'tasks/tasks.html', {'tasks': tasks})


def detail(request, tasks_id):
    tasks = get_object_or_404(Tasks, pk=tasks_id)
    return render(request, 'tasks/detail.html', {'tasks': tasks})

theory/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Theory


def home(request):
    return render(request, 'theory/home.html')


def theory(request):
    theorys = Theory.objects.all()
    return render(request, 'theory/theory.html', {'theorys': theorys})


def detail(request, theory_id):
    theory = get_object_or_404(Theory, pk=theory_id)
    return render(request, 'theory/detail.html', {'theory': theory})

questions/templates/questions/detail.html
{% extends 'theory/base.html' %}
{% block content %}

<br>
<br>
<br>
<div class="container text-center">
    <p><font size="6">{{questions.description}}</font></p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <a href="{% url 'questions:questions' %}"><font size="6"><- Назад</font></a>
</div>

{% endblock %}

questions/templates/questions/questions.html
{% extends 'theory/base.html' %}
{% block content %}

<br>
<div class="container text-center">
    <h1>Контрольные вопросы</h1>
    <br>
    <p><font size="6">Блок контрольных вопросов - это удобный и эффективный инструмент для тестирования знаний и
        проверки уровня подготовки. В этом блоке Вы найдете разнообразные задания, покрывающие различные темы,
        от базовых до продвинутых. Блок контрольных вопросов содержит как теоретические, так и практические задания,
        позволяя ученикам оценить свой уровень понимания материала. Контрольные вопросы помогут прокачать умение
        решения математических задач, повысить уверенность в себе и подготовиться к экзаменам.</font></p>


<br>
<br>
<br>

    <style>
   .btn {
    display: inline-block; /* Строчно-блочный элемент */
    background: #8C959D; /* Серый цвет фона */
    color: #fff; /* Белый цвет текста */
    padding: 1rem 1.5rem; /* Поля вокруг текста */
    text-decoration: none; /* Убираем подчёркивание */
    border-radius: 5px; /* Скругляем уголки */
   }
   </style>

{% for question in questions %}
<a href="{% url 'questions:detail' question.id %}" class="btn"><h2>{{question.title}}</h2></a>
    <br>
    <br>
    <br>
{% endfor %}

</div>

{% endblock %}

tasks/templates/tasks/detail.html
{% extends 'theory/base.html' %}
{% block content %}

<br>
<br>
<br>
<div class="container text-center">
    {% load static %}
    <p>{{tasks.description}}</p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <a href="{% url 'tasks:tasks' %}"><font size="6"><- Назад</font></a>
</div>

{% endblock %}

tasks/templates/tasks/tasks.html
{% extends 'theory/base.html' %}
{% block content %}

<br>
<div class="container text-center">
    <h1>Задачи</h1>
    <br>
    <p><font size="6">Блок задач по математике представляет собой увлекательную коллекцию задач,
      которые помогут развивать логическое мышление и улучшать навыки решения математических проблем.
      В этом блоке Вы найдете широкий спектр заданий, начиная с простейших математических головоломок,
      и заканчивая сложными уровнями, которые предложат опытным математикам задуматься. Наши задачи позволят
      Вам насладиться увлекательным миром математики, остроумно находить новые решения и получать
      удовольствие от каждого решенного задания.</font></p>


<br>
<br>
<br>

    <style>
   .btn {
    display: inline-block; /* Строчно-блочный элемент */
    background: #8C959D; /* Серый цвет фона */
    color: #fff; /* Белый цвет текста */
    padding: 1rem 1.5rem; /* Поля вокруг текста */
    text-decoration: none; /* Убираем подчёркивание */
    border-radius: 5px; /* Скругляем уголки */
   }
   </style>

{% for task in tasks %}
<a href="{% url 'tasks:detail' task.id %}" class="btn"><h2>{{task.title}}</h2></a>
    <br>
    <br>
    <br>
{% endfor %}

</div>

{% endblock %}

theory/templates/theory/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="">Навигация</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Домашняя страница</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'theory:theory' %}">Теория</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'questions:questions' %}">Контрольные вопросы</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tasks:tasks' %}">Задачи</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <title>Math Theory</title>

    <style>
      .gradient {
      background: rgb(217,216,217);
      background: radial-gradient(circle, rgba(217,216,217,0.5970763305322129) 0%, rgba(213,213,191,0.5018382352941176) 50%, rgba(152,204,196,0.4990371148459384) 100%);
      }
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body class="gradient">
    <br>
    <br>
    <br>
    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

theory/templates/theory/detail.html
{% extends 'theory/base.html' %}
{% block content %}

<br>
<br>
<br>
<div class="container text-center">
    <p><font size="6">{{theory.description}}</font></p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <a href="{% url 'theory:theory' %}"><font size="6"><- Назад</font></a>
</div>

{% endblock %}

theory/templates/theory/home.html
{% extends 'theory/base.html' %}
{% block content %}

<br>
<div class="container text-center">
    <h1>Добро пожаловать!</h1>
    <br>
    <p><font size="6">Добро пожаловать на сайт, посвященный математике!
        Здесь вы найдете теорию, контрольные вопросы и практические задания по различным темам.
        Мы разработали материалы для учебы с нулевого уровня до различных ступеней обучения,
        включая школьные и университетские программы.
        На главной странице вы увидите разделы теории, контрольных вопросов и практики.
        Вы можете нажать на любой из них, чтобы получить доступ к соответствующим материалам.
        Мы заинтересованы в том, чтобы облегчить вашу самостоятельную подготовку, поэтому теория изложена так,
        как будто вы разговариваете об этой теме с другом. Никаких сухих формул и занудных лекций!
        Знания по математике пригодятся вам в любой области деятельности, будь то оценка эффективности бизнеса,
        инвестирование в финансовые инструменты, моделирование процессов в науке и технике и т.д.
        Начните изучение математики сейчас!</font></p>

<br>
<br>
<br>
    <style>
   .btn {
    display: inline-block; /* Строчно-блочный элемент */
    background: #8C959D; /* Серый цвет фона */
    color: #fff; /* Белый цвет текста */
    padding: 1rem 3rem; /* Поля вокруг текста */
    text-decoration: none; /* Убираем подчёркивание */
    border-radius: 5px; /* Скругляем уголки */
    margin-left: 30px;
   }
   </style>

    <a href="{% url 'theory:theory' %}" class="btn">Теория</a>
    <a href="{% url 'questions:questions' %}" class="btn">Контрольные вопросы</a>
    <a href="{% url 'tasks:tasks' %}" class="btn">Задачи</a>

</div>

{% endblock %}

theory/templates/theory/theory.html
{% extends 'theory/base.html' %}
{% block content %}

<br>
<div class="container text-center">
    <h1>Теория</h1>
    <br>
    <p><font size="6">Блок "Теория" на нашем сайте представляет собой ценный инструмент для всех,
    кто стремится получить более глубокое понимание различных математических концепций.
    Здесь вы найдете четкое объяснение основных теорем и законов.
    Благодаря наглядной форме представления материала и легкому языку,
    вы легко сможете вникнуть и научиться применять теорию на практике.
        Приятного обучения!</font></p>


<br>
<br>
<br>
    <style>
   .btn {
    display: inline-block; /* Строчно-блочный элемент */
    background: #8C959D; /* Серый цвет фона */
    color: #fff; /* Белый цвет текста */
    padding: 1rem 1.5rem; /* Поля вокруг текста */
    text-decoration: none; /* Убираем подчёркивание */
    border-radius: 5px; /* Скругляем уголки */
   }
   </style>

{% for theory in theorys %}
<a href="{% url 'theory:detail' theory.id %}" class="btn"><h2>{{theory.title}}</h2></a>
    <br>
    <br>
    <br>
{% endfor %}

</div>

{% endblock %}